import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text } from 'react-native';
import { Link } from 'expo-router';
import { AuthError, AuthShell } from '@/components/auth/auth-shell';
import { AuthInput } from '@/components/auth/auth-input';
import { useAuth } from '@/providers/auth-provider';
import { Colors, Spacing } from '@/constants/theme';

export default function ForgotPasswordScreen() { const { resetPassword } = useAuth(); const [email, setEmail] = useState(''); const [error, setError] = useState<string | null>(null); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const submit = async () => { if (!email.trim() || !email.includes('@')) return setError('Please enter a valid email address.'); setError(null); setLoading(true); try { await resetPassword(email); setSent(true); } catch (value) { setError(value instanceof Error ? value.message : 'We could not send the reset email. Please try again.'); } finally { setLoading(false); } }; return <AuthShell eyebrow="ACCOUNT RECOVERY" title="Reset your password." subtitle={sent ? 'If an account exists for that email, we sent a reset link.' : 'Enter your email and we’ll send a secure reset link.'} footer={<Link href="/sign-in" style={styles.link}>Back to Sign In</Link>}>{sent ? <Text style={styles.message}>Check your inbox and follow the link to choose a new password.</Text> : <><AuthInput label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} autoComplete="email" placeholder="you@example.com" /><AuthError message={error} /><Pressable accessibilityRole="button" accessibilityLabel="Send reset link" disabled={loading} onPress={submit} style={styles.primary}>{loading ? <ActivityIndicator color={Colors.text} /> : <Text style={styles.primaryText}>Send Reset Link</Text>}</Pressable></>}</AuthShell>; }
const styles = StyleSheet.create({ primary: { minHeight: 52, borderRadius: 999, backgroundColor: Colors.accent, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.five }, primaryText: { color: Colors.text, fontSize: 16, fontWeight: '800' }, message: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24 }, link: { color: Colors.accentSecondary, fontSize: 15, fontWeight: '800' } });
