import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text } from 'react-native';
import { Link, router } from 'expo-router';
import { AuthDivider, AuthError, AuthFooterLink, AuthShell } from '@/components/auth/auth-shell';
import { AuthInput } from '@/components/auth/auth-input';
import { PasswordInput } from '@/components/auth/password-input';
import { SocialAuthButton } from '@/components/auth/social-auth-button';
import { useAuth } from '@/providers/auth-provider';
import { Colors, Spacing } from '@/constants/theme';

export default function SignInScreen() { const { signIn } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const submit = async () => { if (!email.trim() || !email.includes('@')) { setError('Please enter a valid email address.'); return; } if (!password) { setError('Please enter your password.'); return; } setError(null); setLoading(true); try { await signIn(email, password); router.replace('/'); } catch (value) { setError(value instanceof Error ? value.message : 'We could not sign you in. Please try again.'); } finally { setLoading(false); } }; return <AuthShell eyebrow="WELCOME BACK" title="Continue where you left off." subtitle="Your listening library is waiting for you." footer={<AuthFooterLink prompt="Don’t have an account?" label="Create account" href="/sign-up" />}><AuthInput label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} autoComplete="email" placeholder="you@example.com" /><PasswordInput value={password} onChangeText={setPassword} autoCapitalize="none" autoComplete="password" placeholder="Your password" /><Link href="/forgot-password" style={styles.forgot}>Forgot password?</Link><AuthError message={error} /><Pressable accessibilityRole="button" accessibilityLabel="Sign in" disabled={loading} onPress={submit} style={styles.primary}>{loading ? <ActivityIndicator color={Colors.text} /> : <Text style={styles.primaryText}>Sign In</Text>}</Pressable><AuthDivider /><SocialAuthButton provider="Google" /><SocialAuthButton provider="Apple" /></AuthShell>; }
const styles = StyleSheet.create({ forgot: { color: Colors.accentSecondary, alignSelf: 'flex-end', fontSize: 13, fontWeight: '700', marginTop: Spacing.three }, primary: { minHeight: 52, borderRadius: 999, backgroundColor: Colors.accent, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.five }, primaryText: { color: Colors.text, fontSize: 16, fontWeight: '800' } });
