import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text } from 'react-native';
import { Link, router } from 'expo-router';
import { AuthDivider, AuthError, AuthFooterLink, AuthShell } from '@/components/auth/auth-shell';
import { AuthInput } from '@/components/auth/auth-input';
import { PasswordInput } from '@/components/auth/password-input';
import { SocialAuthButton } from '@/components/auth/social-auth-button';
import { useAuth } from '@/providers/auth-provider';
import { Colors, Spacing } from '@/constants/theme';

export default function SignUpScreen() { const { signUp } = useAuth(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState<string | null>(null); const [confirmation, setConfirmation] = useState(false); const [loading, setLoading] = useState(false); const submit = async () => { if (!name.trim()) return setError('Please enter your display name.'); if (!email.trim() || !email.includes('@')) return setError('Please enter a valid email address.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (password !== confirm) return setError("Your passwords don't match."); setError(null); setLoading(true); try { const result = await signUp(name, email, password); if (result.needsEmailConfirmation) setConfirmation(true); else router.replace('/'); } catch (value) { setError(value instanceof Error ? value.message : 'We could not create your account. Please try again.'); } finally { setLoading(false); } }; if (confirmation) return <AuthShell eyebrow="CHECK YOUR EMAIL" title="One more step." subtitle={`We sent a confirmation link to ${email.trim()}. Open it to finish creating your account.`} footer={<AuthFooterLink prompt="Already confirmed?" label="Sign in" href="/sign-in" />}><Text style={styles.confirmation}>After confirming, return here and sign in with your new account.</Text><Link href="/sign-in" style={styles.primaryLink}>Go to Sign In</Link></AuthShell>; return <AuthShell eyebrow="START LISTENING" title="Create your account." subtitle="Your books, progress, and memories stay with you wherever you listen." footer={<AuthFooterLink prompt="Already have an account?" label="Sign in" href="/sign-in" />}><AuthInput label="Display name" value={name} onChangeText={setName} autoCapitalize="words" autoComplete="name" placeholder="Your name" /><AuthInput label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} autoComplete="email" placeholder="you@example.com" /><PasswordInput value={password} onChangeText={setPassword} autoCapitalize="none" autoComplete="new-password" placeholder="At least 6 characters" /><PasswordInput label="Confirm password" value={confirm} onChangeText={setConfirm} autoCapitalize="none" autoComplete="new-password" placeholder="Repeat your password" /><AuthError message={error} /><Pressable accessibilityRole="button" accessibilityLabel="Create account" disabled={loading} onPress={submit} style={styles.primary}>{loading ? <ActivityIndicator color={Colors.text} /> : <Text style={styles.primaryText}>Create Account</Text>}</Pressable><AuthDivider /><SocialAuthButton provider="Google" /><SocialAuthButton provider="Apple" /></AuthShell>; }
const styles = StyleSheet.create({ primary: { minHeight: 52, borderRadius: 999, backgroundColor: Colors.accent, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.five }, primaryText: { color: Colors.text, fontSize: 16, fontWeight: '800' }, confirmation: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24 }, primaryLink: { color: Colors.accentSecondary, fontSize: 16, fontWeight: '800', marginTop: Spacing.five } });
