import { Link, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { IconButton } from '@/components/common/icon-button';
import { findBook } from '@/data/mock-books';
import { usePlayer } from '@/state/player-context';
import { Colors, Spacing } from '@/constants/theme';

export default function PlayerScreen() { const { bookId } = useLocalSearchParams<{ bookId: string }>(); const book = findBook(bookId); const player = usePlayer(); if (!book) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Book not found</Text><Link href="/" style={styles.link}>Back to home</Link></View></SafeAreaView>; return <SafeAreaView style={styles.safe}><View style={styles.content}><View style={styles.top}><Link href={`/book/${book.id}`} style={styles.close}>‹ Back</Link><Text style={styles.context}>{book.currentChapter}</Text><IconButton symbol="ellipsis" label="More player options" /></View><View style={[styles.cover, { backgroundColor: book.coverColor }]}><Text style={styles.coverText}>{book.coverLabel}</Text></View><Text style={styles.title}>{book.title}</Text><Text style={styles.author}>{book.author} · {book.currentChapter}</Text><View style={styles.track}><View style={[styles.fill, { width: `${player.progress}%` }]} /></View><View style={styles.times}><Text style={styles.time}>12:48</Text><Text style={styles.time}>{book.remainingTime}</Text></View><View style={styles.controls}><Text style={styles.skip}>↶ 15</Text><Pressable accessibilityRole="button" accessibilityLabel={player.isPlaying ? 'Pause playback' : 'Play playback'} onPress={player.togglePlaying} style={styles.play}><Text style={styles.playText}>{player.isPlaying ? 'Ⅱ' : '▶'}</Text></Pressable><Text style={styles.skip}>15 ↷</Text></View><View style={styles.actions}><Pressable onPress={() => player.setPlaybackRate(player.playbackRate === 1 ? 1.25 : 1)} accessibilityRole="button"><Text style={styles.action}>{player.playbackRate}×</Text></Pressable><Pressable onPress={player.saveRemember} accessibilityRole="button" accessibilityLabel="Remember this passage"><Text style={styles.action}>Remember</Text></Pressable><Text style={styles.action}>Sleep timer</Text><Text style={styles.action}>Chapters</Text></View>{player.rememberSaved ? <Text style={styles.saved}>✓ Saved to Remember</Text> : null}</View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, flex: 1, alignItems: 'center' }, top: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, close: { color: Colors.textSecondary, fontSize: 15 }, context: { color: Colors.textSecondary, fontSize: 12, flex: 1, textAlign: 'center' }, cover: { width: 260, height: 300, borderRadius: 20, marginTop: Spacing.seven, justifyContent: 'flex-end', padding: Spacing.seven }, coverText: { color: Colors.text, fontSize: 34, lineHeight: 32, fontWeight: '900' }, title: { color: Colors.text, fontSize: 26, lineHeight: 32, fontWeight: '800', marginTop: Spacing.five, textAlign: 'center' }, author: { color: Colors.textSecondary, fontSize: 14, marginTop: Spacing.one }, track: { width: '100%', height: 5, backgroundColor: '#303540', borderRadius: 3, marginTop: Spacing.seven }, fill: { height: 5, backgroundColor: Colors.accentSecondary, borderRadius: 3 }, times: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginTop: Spacing.two }, time: { color: Colors.textSecondary, fontSize: 12 }, controls: { flexDirection: 'row', alignItems: 'center', gap: Spacing.seven, marginTop: Spacing.five }, skip: { color: Colors.text, fontSize: 15 }, play: { width: 64, height: 64, borderRadius: 32, backgroundColor: Colors.text, alignItems: 'center', justifyContent: 'center' }, playText: { color: Colors.background, fontSize: 22 }, actions: { width: '100%', flexDirection: 'row', justifyContent: 'space-around', marginTop: Spacing.seven }, action: { color: Colors.textSecondary, fontSize: 13 }, saved: { color: Colors.success, fontSize: 14, fontWeight: '700', marginTop: Spacing.five }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, link: { color: Colors.accentSecondary, marginTop: Spacing.three } });
