import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants/theme';
import { getCreatorStoryAnalytics, type CreatorStoryAnalytics } from '@/services/api';

export default function CreatorStoryAnalyticsScreen() {
  const { contentId } = useLocalSearchParams<{ contentId: string }>(); const [range, setRange] = useState<CreatorStoryAnalytics['range']>('30D'); const [data, setData] = useState<CreatorStoryAnalytics | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!contentId) return; void getCreatorStoryAnalytics(contentId, range).then((value) => { setData(value); setError(null); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load analytics.')); }, [contentId, range]);
  const totals = useMemo(() => (data?.daily ?? []).reduce((sum, row) => ({ listeners: sum.listeners + row.unique_listeners, qualified: sum.qualified + row.qualified_listens, minutes: sum.minutes + Math.round(row.listening_seconds / 60), completion: sum.completion + Number(row.average_completion_percent ?? 0), completions: sum.completions + row.completions, favorites: sum.favorites + row.favorites_added, shares: sum.shares + row.shares, followers: sum.followers + row.followers_gained, days: sum.days + 1 }), { listeners: 0, qualified: 0, minutes: 0, completion: 0, completions: 0, favorites: 0, shares: 0, followers: 0, days: 0 }), [data]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Creator Studio</Text></Pressable>{!data && !error ? <ActivityIndicator color={Colors.accentSecondary} /> : error ? <Text style={styles.error}>{error}</Text> : <><Text style={styles.title}>{data?.title}</Text><Text style={styles.heading}>Analytics</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.ranges}>{(['7D', '30D', 'ALL'] as const).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.range, range === item && styles.active]}><Text style={styles.rangeText}>{item === '7D' ? '7 Days' : item === '30D' ? '30 Days' : 'All Time'}</Text></Pressable>)}</ScrollView><Text style={styles.metric}>Unique listeners: {totals.listeners}</Text><Text style={styles.metric}>Qualified listens: {totals.qualified}</Text><Text style={styles.metric}>Listening time: {totals.minutes} min</Text><Text style={styles.metric}>Average completion: {totals.days ? Math.round(totals.completion / totals.days) : 0}%</Text><Text style={styles.metric}>Completions: {totals.completions}</Text><Text style={styles.metric}>Favorites: {totals.favorites}</Text><Text style={styles.metric}>Shares: {totals.shares}</Text><Text style={styles.metric}>Followers gained: {totals.followers}</Text>{totals.listeners === 0 ? <Text style={styles.empty}>No listening data yet. Your analytics will appear when listeners start playing your published stories.</Text> : null}<Text style={styles.heading}>Listening trend</Text>{data?.daily.map((row) => <Text key={row.date} style={styles.row}>{row.date}: {row.unique_listeners} listeners · {Math.round(row.listening_seconds / 60)} min</Text>)}</>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 100 }, back: { color: Colors.accentSecondary, fontWeight: '700' }, title: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: Spacing.seven }, heading: { color: Colors.text, fontSize: 20, fontWeight: '800', marginTop: Spacing.seven, marginBottom: Spacing.three }, ranges: { gap: Spacing.two }, range: { borderColor: Colors.elevated, borderWidth: 1, borderRadius: 999, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, active: { backgroundColor: Colors.accentSecondary, borderColor: Colors.accentSecondary }, rangeText: { color: Colors.text, fontWeight: '700' }, metric: { color: Colors.text, backgroundColor: Colors.surface, borderRadius: 12, padding: Spacing.four, marginBottom: Spacing.two }, row: { color: Colors.textSecondary, paddingVertical: Spacing.two }, empty: { color: Colors.textSecondary, lineHeight: 22, marginTop: Spacing.four }, error: { color: Colors.danger, marginTop: Spacing.seven } });
