import { Router } from "express";
import { z } from "zod";
import type { ApiEnv } from "../../config/env";
import { createSupabaseClient } from "../../lib/supabase";
import { scoreCatalogItem } from "./recommendations";

const searchSchema = z.object({ q: z.string().trim().max(120).optional(), genre: z.string().trim().max(80).optional(), language: z.string().trim().max(16).optional(), type: z.enum(["STORY", "BOOK", "ARTICLE", "PODCAST", "OTHER"]).optional(), limit: z.coerce.number().int().min(1).max(50).default(20) });

export function createCatalogRouter(env: ApiEnv) {
  const router = Router();
  router.get("/genres", async (req, res, next) => { try { const { data, error } = await createSupabaseClient(env).from("genres").select("id,name,slug,sort_order").eq("is_active", true).order("sort_order"); if (error) { console.error(JSON.stringify({ event: "catalog_genres_query_failed", requestId: res.getHeader("X-Request-Id"), operation: "catalog.genres", code: error.code, message: error.message })); throw error; } res.json({ data: data ?? [] }); } catch (error) { next(error); } });
  router.get(["/", "/search"], async (req, res, next) => { try { const input = searchSchema.parse(req.query); const client = createSupabaseClient(env); let query = client.from("catalog_content").select("id,title,author_display_name,description,content_type,language,cover_storage_key,estimated_duration_seconds,published_at,creator_id,content_genres(genre_id,genres(name,slug))").eq("status", "PUBLISHED").eq("visibility", "PUBLIC").limit(input.limit); if (input.q) query = query.or(`title.ilike.%${input.q}%,author_display_name.ilike.%${input.q}%,description.ilike.%${input.q}%`); if (input.language) query = query.eq("language", input.language); if (input.type) query = query.eq("content_type", input.type); const { data, error } = await query.order("published_at", { ascending: false }); if (error) throw error; const content = (data ?? []).filter((item) => !input.genre || JSON.stringify(item.content_genres).toLowerCase().includes(input.genre.toLowerCase())); res.json({ data: { content, creators: [] } }); } catch (error) { next(error); } });
  router.get("/recommendations", async (req, res, next) => { try { const input = searchSchema.parse(req.query); const { data, error } = await createSupabaseClient(env).from("catalog_content").select("id,title,author_display_name,description,content_type,language,published_at,creator_id,content_genres(genre_id,genres(name,slug))").eq("status", "PUBLISHED").eq("visibility", "PUBLIC").limit(input.limit); if (error) throw error; const now = Date.now(); const items = (data ?? []).map((item) => ({ ...item, recommendationScore: scoreCatalogItem({ genreMatch: Boolean(input.genre && JSON.stringify(item.content_genres).toLowerCase().includes(input.genre.toLowerCase())), daysSincePublished: item.published_at ? Math.max(0, (now - Date.parse(item.published_at)) / 86400000) : 365, explorationEligible: true }) })).sort((a, b) => b.recommendationScore - a.recommendationScore); res.json({ data: items }); } catch (error) { next(error); } });
  router.get("/content/:contentId", async (req, res, next) => { try { const id = z.string().uuid().parse(req.params.contentId); const { data, error } = await createSupabaseClient(env).from("catalog_content").select("id,title,author_display_name,description,content_type,language,cover_storage_key,estimated_duration_seconds,published_at,creator_id,content_genres(genre_id,genres(name,slug))").eq("id", id).eq("status", "PUBLISHED").eq("visibility", "PUBLIC").maybeSingle(); if (error) throw error; if (!data) return res.status(404).json({ error: { code: "CONTENT_NOT_FOUND", message: "Story not found." } }); res.json({ data }); } catch (error) { next(error); } });
  return router;
}
