import { Link, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ChapterRow } from '@/components/library/chapter-row';
import { IconButton } from '@/components/common/icon-button';
import { PrimaryButton } from '@/components/common/primary-button';
import { findBook } from '@/data/mock-books';
import { Colors, Spacing } from '@/constants/theme';

export default function BookScreen() { const { bookId } = useLocalSearchParams<{ bookId: string }>(); const book = findBook(bookId); if (!book) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Book not found</Text><Link href="/library" style={styles.link}>Back to library</Link></View></SafeAreaView>; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Link href="/library" style={styles.back}>‹ Library</Link><View style={[styles.cover, { backgroundColor: book.coverColor }]}><Text style={styles.coverText}>{book.coverLabel}</Text></View><Text style={styles.title}>{book.title}</Text><Text style={styles.author}>{book.author}</Text><Text style={styles.meta}>{book.progress}% complete · {book.currentChapter}</Text><Link href={`/player/${book.id}`} asChild><PrimaryButton title="Continue Listening" style={styles.primary} /></Link><View style={styles.actions}><IconButton symbol="heart" label="Favorite book" /><IconButton symbol="arrow.down.circle" label="Download book" /><IconButton symbol="ellipsis" label="More options" /></View><View style={styles.section}><Text style={styles.sectionTitle}>Chapters</Text>{book.chapters.map((chapter) => <ChapterRow key={chapter.id} chapter={chapter} />)}</View><View style={styles.section}><Text style={styles.sectionTitle}>About this book</Text><Text style={styles.description}>{book.description}</Text></View></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 150 }, back: { color: Colors.accentSecondary, fontSize: 15, fontWeight: '700' }, cover: { width: 190, height: 250, borderRadius: 16, marginTop: Spacing.five, justifyContent: 'flex-end', padding: Spacing.five }, coverText: { color: Colors.text, fontSize: 25, lineHeight: 24, fontWeight: '900' }, title: { color: Colors.text, fontSize: 28, lineHeight: 34, fontWeight: '800', marginTop: Spacing.five }, author: { color: Colors.textSecondary, fontSize: 15, marginTop: Spacing.one }, meta: { color: Colors.accentSecondary, fontSize: 13, marginTop: Spacing.three }, primary: { marginTop: Spacing.five }, actions: { flexDirection: 'row', gap: Spacing.three, marginTop: Spacing.four }, section: { marginTop: Spacing.seven }, sectionTitle: { color: Colors.text, fontSize: 20, fontWeight: '800', marginBottom: Spacing.two }, description: { color: Colors.textSecondary, fontSize: 15, lineHeight: 23 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, link: { color: Colors.accentSecondary, marginTop: Spacing.three } });
