import { useEffect, useState } from 'react';
import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Colors, Spacing } from '@/constants/theme';
import { completeCreatorUpload, createCreatorSubmission, getCatalogGenres, getCreatorUploadUrl, submitCreatorSubmission, type CatalogGenre } from '@/services/api';

export default function CreatorSubmitScreen() {
  const [title, setTitle] = useState(''); const [shortDescription, setShortDescription] = useState(''); const [description, setDescription] = useState(''); const [language, setLanguage] = useState('en'); const [tags, setTags] = useState(''); const [audioSourceType, setAudioSourceType] = useState<'OWN_RECORDING' | 'PROFESSIONAL_STUDIO' | 'EXTERNAL_AI' | 'OTHER_AUTHORIZED_SOURCE' | ''>(''); const [externalProvider, setExternalProvider] = useState(''); const [genres, setGenres] = useState<CatalogGenre[]>([]); const [selectedGenres, setSelectedGenres] = useState<string[]>([]); const [asset, setAsset] = useState<DocumentPicker.DocumentPickerAsset | null>(null); const [rightsAccepted, setRightsAccepted] = useState(false); const [loading, setLoading] = useState(false); const [phase, setPhase] = useState(''); const [genresLoading, setGenresLoading] = useState(true); const [genresError, setGenresError] = useState(false);
  useEffect(() => { void getCatalogGenres().then(setGenres).catch(() => setGenresError(true)).finally(() => setGenresLoading(false)); }, []);
  function retryGenres() { setGenresLoading(true); setGenresError(false); void getCatalogGenres().then(setGenres).catch(() => setGenresError(true)).finally(() => setGenresLoading(false)); }
  function toggleGenre(id: string) { setSelectedGenres((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }
  async function choosePdf() { const result = await DocumentPicker.getDocumentAsync({ type: 'application/pdf', copyToCacheDirectory: true, multiple: false }); if (!result.canceled) setAsset(result.assets[0]); }
  async function submit() { if (!title.trim() || !selectedGenres.length || !asset || !rightsAccepted) { Alert.alert('Incomplete submission', 'Add story details, choose at least one genre and PDF, and accept the rights declaration.'); return; } setLoading(true); try { setPhase('Preparing upload…'); const draft = await createCreatorSubmission({ title, description, genreIds: selectedGenres }); const upload = await getCreatorUploadUrl(draft.id, { originalFilename: asset.name, mimeType: 'application/pdf', sizeBytes: asset.size ?? 0 }); setPhase('Uploading manuscript…'); const result = await new File(asset.uri).upload(upload.uploadUrl, { httpMethod: 'PUT', headers: upload.requiredHeaders, uploadType: 0 }); if (result.status < 200 || result.status >= 300) throw new Error('The manuscript upload failed.'); setPhase('Verifying upload…'); await completeCreatorUpload(draft.id); setPhase('Submitting for review…'); await submitCreatorSubmission(draft.id, { title, description, genreIds: selectedGenres, rightsDeclaration: 'I own this work or have the necessary rights to submit it to PlayBook.', declarationVersion: 'v1' }); router.replace('/creator-studio' as never); } catch (cause) { Alert.alert('Submission failed', cause instanceof Error ? cause.message : 'Unable to submit this story.'); } finally { setLoading(false); setPhase(''); } }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Submit a story</Text><Text style={styles.label}>Story details</Text><TextInput placeholder="Title" placeholderTextColor={Colors.textSecondary} value={title} onChangeText={setTitle} style={styles.input} /><TextInput placeholder="Description" placeholderTextColor={Colors.textSecondary} value={description} onChangeText={setDescription} multiline style={styles.input} /><Text style={styles.label}>Genres</Text>{genresLoading ? <ActivityIndicator color={Colors.accentSecondary} /> : genresError ? <View><Text style={styles.meta}>Genres could not be loaded.</Text><Pressable onPress={retryGenres}><Text style={styles.retry}>Retry</Text></Pressable></View> : genres.length ? <View style={styles.genreWrap}>{genres.map((genre) => <Pressable key={genre.id} onPress={() => toggleGenre(genre.id)} style={[styles.genre, selectedGenres.includes(genre.id) && styles.genreSelected]}><Text style={styles.genreText}>{genre.name}{selectedGenres.includes(genre.id) ? ' ✓' : ''}</Text></Pressable>)}</View> : <Text style={styles.meta}>No genres are available yet.</Text>}<Text style={styles.label}>Manuscript</Text><Pressable style={styles.fileButton} onPress={() => void choosePdf()}><Text style={styles.buttonText}>{asset ? `Selected: ${asset.name}` : 'Choose PDF'}</Text></Pressable>{asset ? <Text style={styles.meta}>{Math.round((asset.size ?? 0) / 1024 / 1024 * 10) / 10} MB · PDF only</Text> : null}<Pressable style={styles.rights} onPress={() => setRightsAccepted((value) => !value)}><Text style={styles.checkbox}>{rightsAccepted ? '☑' : '☐'}</Text><Text style={styles.rightsText}>I own this work or have the necessary rights to submit it.</Text></Pressable>{phase ? <View style={styles.progress}><ActivityIndicator color={Colors.accentSecondary} /><Text style={styles.meta}>{phase}</Text></View> : null}<Pressable disabled={loading} style={styles.button} onPress={() => void submit()}><Text style={styles.buttonText}>{loading ? phase : 'Submit for review'}</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 100 }, title: { color: Colors.text, fontSize: 28, fontWeight: '800', marginBottom: Spacing.five }, label: { color: Colors.text, fontSize: 16, fontWeight: '800', marginTop: Spacing.four, marginBottom: Spacing.two }, input: { backgroundColor: Colors.surface, color: Colors.text, borderRadius: 12, padding: Spacing.four, marginBottom: Spacing.three, minHeight: 52 }, genreWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two }, genre: { borderWidth: 1, borderColor: Colors.elevated, borderRadius: 999, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, genreSelected: { backgroundColor: Colors.accent, borderColor: Colors.accent }, genreText: { color: Colors.text }, fileButton: { backgroundColor: Colors.surface, borderRadius: 12, padding: Spacing.four }, meta: { color: Colors.textSecondary, marginTop: Spacing.two }, retry: { color: Colors.accentSecondary, fontWeight: '800', marginTop: Spacing.two }, rights: { flexDirection: 'row', alignItems: 'center', marginTop: Spacing.five, gap: Spacing.two }, checkbox: { color: Colors.accentSecondary, fontSize: 24 }, rightsText: { color: Colors.textSecondary, flex: 1 }, progress: { alignItems: 'center', marginTop: Spacing.five }, button: { backgroundColor: Colors.accentSecondary, borderRadius: 12, padding: Spacing.four, alignItems: 'center', marginTop: Spacing.five }, buttonText: { color: Colors.background, fontWeight: '800' } });
