import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { router, useLocalSearchParams } from 'expo-router';
import { Colors, Spacing } from '@/constants/theme';
import { completeCreatorAudioUpload, completeCreatorCoverUpload, getCreatorAudioUploadUrl, getCreatorCoverUploadUrl, getCreatorSubmission, updateCreatorSubmission } from '@/services/api';

export default function CreatorContentEditScreen() {
  const { submissionId } = useLocalSearchParams<{ submissionId?: string }>();
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [language, setLanguage] = useState('en'); const [altText, setAltText] = useState(''); const [coverKey, setCoverKey] = useState<string | null>(null); const [audioName, setAudioName] = useState<string | null>(null); const [audioType, setAudioType] = useState('OWN_RECORDING'); const [provider, setProvider] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!submissionId) return; void getCreatorSubmission(submissionId).then((item) => { setTitle(item.title); setDescription(item.description ?? ''); setLanguage(item.language ?? 'en'); }).catch(() => setError('This content could not be loaded.')).finally(() => setLoading(false)); }, [submissionId]);
  async function cover() { if (!submissionId) return; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 }); if (result.canceled) return; const image = result.assets[0]; setBusy(true); try { const upload = await getCreatorCoverUploadUrl(submissionId, { mimeType: image.mimeType === 'image/png' ? 'image/png' : 'image/jpeg', sizeBytes: image.fileSize ?? 1 }); const response = await new File(image.uri).upload(upload.uploadUrl, { httpMethod: 'PUT', headers: upload.requiredHeaders, uploadType: 0 }); if (response.status < 200 || response.status >= 300) throw new Error('upload'); await completeCreatorCoverUpload(submissionId, upload.key, altText); setCoverKey(upload.key); } catch { Alert.alert("We couldn't upload this cover", 'Please choose another image.'); } finally { setBusy(false); } }
  async function audio() { if (!submissionId) return; const result = await DocumentPicker.getDocumentAsync({ type: ['audio/mpeg', 'audio/mp4', 'audio/wav', 'audio/flac'] }); if (result.canceled) return; const item = result.assets[0]; setBusy(true); try { const mimeType = item.mimeType === 'audio/mp4' ? 'audio/mp4' : item.mimeType === 'audio/wav' ? 'audio/wav' : 'audio/mpeg'; const upload = await getCreatorAudioUploadUrl(submissionId, { mimeType, sizeBytes: item.size ?? 1, audioSourceType: audioType, externalAudioProviderName: provider || undefined }); const response = await new File(item.uri).upload(upload.uploadUrl, { httpMethod: 'PUT', headers: upload.requiredHeaders, uploadType: 0 }); if (response.status < 200 || response.status >= 300) throw new Error('upload'); await completeCreatorAudioUpload(submissionId, upload.key, { audioSourceType: audioType, externalAudioProviderName: provider || undefined, rightsDeclaration: 'I own or have the necessary rights to the manuscript and audio recording, including applicable performance, voice, and distribution rights.', rightsVersion: 'v1' }); setAudioName(item.name); } catch { Alert.alert('Audio upload failed', 'The audio could not be validated.'); } finally { setBusy(false); } }
  async function save() { if (!submissionId || !title.trim()) return setError('Add a title before saving.'); setBusy(true); try { await updateCreatorSubmission(submissionId, { title: title.trim(), description: description.trim(), language, coverAltText: altText, coverStorageKey: coverKey ?? undefined, audioSourceType: audioType as never, externalAudioProviderName: provider || undefined }); router.back(); } catch { setError('This content cannot be edited in its current state.'); } finally { setBusy(false); } }
  if (loading) return <SafeAreaView style={styles.safe}><ActivityIndicator color={Colors.accentSecondary} /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.top}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.heading}>Edit Story</Text><Pressable disabled={busy} onPress={() => void save()}><Text style={styles.save}>Save</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><View style={styles.cover}><Text style={styles.coverText}>{coverKey ? '✓' : title.slice(0, 1)}</Text></View><Pressable style={styles.control} disabled={busy} onPress={() => void cover()}><Text style={styles.controlText}>{coverKey ? 'Replace Cover' : '+ Upload Cover'}</Text></Pressable>{coverKey ? <Pressable onPress={() => setCoverKey(null)}><Text style={styles.remove}>Remove Cover</Text></Pressable> : null}<Text style={styles.label}>Cover Alt Text</Text><TextInput value={altText} onChangeText={setAltText} placeholder="Describe the cover image" placeholderTextColor={Colors.textSecondary} style={styles.input} /><Text style={styles.label}>Title</Text><TextInput value={title} onChangeText={setTitle} style={styles.input} /><Text style={styles.label}>Description</Text><TextInput value={description} onChangeText={setDescription} multiline style={[styles.input, styles.multiline]} /><Text style={styles.label}>Language</Text><TextInput value={language} onChangeText={setLanguage} style={styles.input} /><Text style={styles.label}>Audio source</Text>{['OWN_RECORDING', 'PROFESSIONAL_STUDIO', 'EXTERNAL_AI', 'OTHER_AUTHORIZED_SOURCE'].map((value) => <Pressable key={value} style={styles.option} onPress={() => setAudioType(value)}><Text style={styles.radio}>{audioType === value ? '●' : '○'}</Text><Text style={styles.value}>{value.replaceAll('_', ' ')}</Text></Pressable>)}{audioType === 'EXTERNAL_AI' ? <TextInput value={provider} onChangeText={setProvider} placeholder="AI provider (optional)" placeholderTextColor={Colors.textSecondary} style={styles.input} /> : null}<Pressable style={styles.control} disabled={busy} onPress={() => void audio()}><Text style={styles.controlText}>{audioName ? `Replace Audio · ${audioName}` : '+ Upload Audio'}</Text></Pressable><Text style={styles.meta}>Generate with PlayBook AI · Coming Soon</Text>{error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: Spacing.five, borderBottomWidth: 1, borderBottomColor: Colors.elevated }, back: { color: Colors.text, fontSize: 32 }, heading: { color: Colors.text, fontSize: 20, fontWeight: '800' }, save: { color: Colors.accentSecondary, fontWeight: '800' }, content: { padding: Spacing.five, paddingBottom: 120 }, cover: { height: 150, backgroundColor: Colors.elevated, alignItems: 'center', justifyContent: 'center' }, coverText: { color: Colors.text, fontSize: 64, fontWeight: '800' }, control: { backgroundColor: Colors.surface, borderRadius: 12, padding: Spacing.four, alignItems: 'center', marginTop: Spacing.three }, controlText: { color: Colors.accentSecondary, fontWeight: '800' }, remove: { color: Colors.danger, textAlign: 'center', marginTop: Spacing.two }, label: { color: Colors.textSecondary, marginTop: Spacing.five, marginBottom: Spacing.two }, input: { color: Colors.text, borderBottomWidth: 1, borderBottomColor: Colors.elevated, paddingVertical: Spacing.three, fontSize: 17 }, multiline: { minHeight: 90, textAlignVertical: 'top' }, option: { flexDirection: 'row', gap: Spacing.two, paddingVertical: Spacing.two }, radio: { color: Colors.accentSecondary, fontSize: 18 }, value: { color: Colors.text }, meta: { color: Colors.textSecondary, marginTop: Spacing.three }, error: { color: Colors.danger, marginTop: Spacing.four } });
