import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants/theme';
import { createCreatorProfile, getCreatorProfile, updateCreatorProfile } from '@/services/api';

export default function CreatorProfileScreen() {
  const { edit } = useLocalSearchParams<{ edit?: string }>(); const editing = edit === 'true';
  const [displayName, setDisplayName] = useState(''); const [bio, setBio] = useState(''); const [language, setLanguage] = useState(''); const [avatarUrl, setAvatarUrl] = useState(''); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!editing) return; void getCreatorProfile().then((profile) => { if (!profile) { setError('Creator profile not found.'); return; } setDisplayName(profile.display_name); setBio(profile.bio ?? ''); setLanguage(profile.primary_language ?? ''); setAvatarUrl(profile.avatar_url ?? ''); }).catch(() => setError("We couldn't load your creator profile.")).finally(() => setLoading(false)); }, [editing]);
  async function submit() { if (!displayName.trim()) { setError('Add a creator display name.'); return; } setSaving(true); setError(null); try { const input = { displayName, bio, primaryLanguage: language, avatarUrl: avatarUrl || undefined }; if (editing) await updateCreatorProfile(input); else await createCreatorProfile(input); router.replace('/(tabs)/profile' as never); } catch (cause) { setError(cause instanceof Error ? cause.message : editing ? 'Unable to save your creator profile.' : 'Unable to create creator profile.'); } finally { setSaving(false); } }
  if (loading) return <SafeAreaView style={styles.safe}><ActivityIndicator color={Colors.accentSecondary} /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>{editing ? 'Edit Creator Profile' : 'Become a Creator'}</Text><Text style={styles.body}>{editing ? 'Update the public profile fields listeners can see.' : 'Use your existing PlayBook account to publish when your creator profile is approved.'}</Text><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Creator display name" placeholderTextColor={Colors.textSecondary} style={styles.input} /><TextInput value={language} onChangeText={setLanguage} placeholder="Primary language" placeholderTextColor={Colors.textSecondary} style={styles.input} /><TextInput value={avatarUrl} onChangeText={setAvatarUrl} placeholder="Avatar URL (optional)" placeholderTextColor={Colors.textSecondary} autoCapitalize="none" style={styles.input} /><TextInput value={bio} onChangeText={setBio} placeholder="Short bio" placeholderTextColor={Colors.textSecondary} multiline style={[styles.input, styles.bio]} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={saving} onPress={() => void submit()} style={styles.button}>{saving ? <ActivityIndicator color={Colors.text} /> : <Text style={styles.buttonText}>{editing ? 'Save Profile' : 'Create Creator Profile'}</Text>}</Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { flex: 1, padding: Spacing.six }, back: { color: Colors.accentSecondary, fontWeight: '700' }, title: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: Spacing.seven }, body: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24, marginTop: Spacing.two }, input: { backgroundColor: Colors.surface, color: Colors.text, borderRadius: 14, padding: Spacing.four, marginTop: Spacing.four }, bio: { minHeight: 120, textAlignVertical: 'top' }, error: { color: Colors.danger, marginTop: Spacing.three }, button: { backgroundColor: Colors.accent, borderRadius: 999, alignItems: 'center', padding: Spacing.four, marginTop: Spacing.five }, buttonText: { color: Colors.text, fontWeight: '800' } });
