import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuthInput } from '@/components/auth/auth-input';
import { useAuth } from '@/providers/auth-provider';
import { Colors, Spacing } from '@/constants/theme';

export default function ProfileEditScreen() { const { user, profile, updateProfile } = useAuth(); const [name, setName] = useState(profile?.display_name || user?.user_metadata.display_name || ''); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const save = async () => { if (!name.trim()) return setError('Please enter a display name.'); setError(null); setLoading(true); try { await updateProfile(name); router.back(); } catch (value) { setError(value instanceof Error ? value.message : 'We could not update your profile.'); } finally { setLoading(false); } }; return <SafeAreaView style={styles.safe}><View style={styles.content}><Pressable onPress={() => router.back()} accessibilityRole="button"><Text style={styles.back}>‹ Profile</Text></Pressable><Text style={styles.title}>Edit Profile</Text><Text style={styles.subtitle}>Update the name shown in your listening space.</Text><AuthInput label="Display name" value={name} onChangeText={setName} autoCapitalize="words" placeholder="Your name" /><Text style={styles.email}>{user?.email}</Text>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Pressable onPress={save} disabled={loading} accessibilityRole="button" style={styles.button}>{loading ? <ActivityIndicator color={Colors.text} /> : <Text style={styles.buttonText}>Save Changes</Text>}</Pressable></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six }, back: { color: Colors.accentSecondary, fontSize: 15, fontWeight: '700' }, title: { color: Colors.text, fontSize: 30, fontWeight: '800', marginTop: Spacing.seven }, subtitle: { color: Colors.textSecondary, fontSize: 15, lineHeight: 22, marginTop: Spacing.two }, email: { color: Colors.textSecondary, fontSize: 14, marginTop: Spacing.four }, error: { color: Colors.danger, marginTop: Spacing.three }, button: { minHeight: 52, borderRadius: 999, backgroundColor: Colors.accent, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.seven }, buttonText: { color: Colors.text, fontSize: 16, fontWeight: '800' } });
