import { Link, router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { findBook } from '@/data/mock-books';
import { Colors, Spacing } from '@/constants/theme';

const steps = ['Uploading', 'Reading document', 'Finding chapters', 'Creating preview'];
export default function ProcessingScreen() { const { bookId } = useLocalSearchParams<{ bookId: string }>(); const [progress, setProgress] = useState(12); const book = findBook(bookId) ?? findBook('atomic-habits')!; useEffect(() => { const timer = setInterval(() => setProgress((value) => Math.min(value + 11, 100)), 700); return () => clearInterval(timer); }, []); const complete = progress >= 100; const activeStep = Math.min(Math.floor(progress / 25), 3); return <SafeAreaView style={styles.safe}><View style={styles.content}><View style={styles.spinner}><Text style={styles.spinnerText}>{complete ? '✓' : '◌'}</Text></View><Text style={styles.title}>{complete ? 'Your preview is ready' : 'Preparing your book'}</Text><Text style={styles.body}>{complete ? `${book.title} is ready for a first listen.` : 'We’re getting your book ready. You can start listening as soon as the preview is done.'}</Text><View style={styles.steps}>{steps.map((step, index) => <View key={step} style={styles.step}><Text style={[styles.stepIcon, index < activeStep && styles.done]}>{index < activeStep ? '✓' : index === activeStep && !complete ? '•' : '○'}</Text><Text style={[styles.stepText, index <= activeStep && styles.active]}>{step}</Text></View>)}</View><View style={styles.track}><View style={[styles.fill, { width: `${progress}%` }]} /></View><Text style={styles.percent}>{progress}%</Text>{complete ? <Pressable accessibilityRole="button" onPress={() => router.push(`/player/${book.id}`)} style={styles.button}><Text style={styles.buttonText}>Start Listening</Text></Pressable> : <Link href="/" style={styles.link}>Back to home</Link>}</View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { flex: 1, padding: Spacing.six, alignItems: 'center', justifyContent: 'center' }, spinner: { width: 88, height: 88, borderRadius: 44, backgroundColor: Colors.elevated, alignItems: 'center', justifyContent: 'center' }, spinnerText: { color: Colors.accentSecondary, fontSize: 48 }, title: { color: Colors.text, fontSize: 28, fontWeight: '800', marginTop: Spacing.six, textAlign: 'center' }, body: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24, textAlign: 'center', marginTop: Spacing.three }, steps: { width: '100%', marginTop: Spacing.seven, gap: Spacing.three }, step: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three }, stepIcon: { color: Colors.textSecondary, fontSize: 18, width: 20, textAlign: 'center' }, done: { color: Colors.success }, stepText: { color: Colors.textSecondary, fontSize: 15 }, active: { color: Colors.text, fontWeight: '700' }, track: { width: '100%', height: 6, backgroundColor: '#303540', borderRadius: 3, marginTop: Spacing.seven }, fill: { height: 6, backgroundColor: Colors.accentSecondary, borderRadius: 3 }, percent: { color: Colors.textSecondary, fontSize: 12, marginTop: Spacing.two }, button: { backgroundColor: Colors.accent, borderRadius: 999, paddingHorizontal: Spacing.six, paddingVertical: Spacing.four, marginTop: Spacing.seven }, buttonText: { color: Colors.text, fontSize: 16, fontWeight: '800' }, link: { color: Colors.accentSecondary, fontSize: 15, fontWeight: '700', marginTop: Spacing.seven } });
