import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Colors, Spacing } from '@/constants/theme';
import { acceptCreatorGuidelines, applyForCreatorVerification, applyForMonetization, deleteCreatorSubmission, getCreatorDashboard, getCreatorMonetization, getCreatorStories, getCreatorVerification, listCreatorSubmissions, submitCreatorSubmissionDirect, unpublishCreatorSubmission, type CreatorDashboard, type CreatorMonetization, type CreatorProfile, type CreatorVerification } from '@/services/api';
import { VerifiedBadge } from '@/components/verified-badge';
import { CreatorEarnPanel } from '@/components/creator-earn-panel';

type Tab = 'Dashboard' | 'Content' | 'Analytics' | 'Earn' | 'Profile';
type Submission = Awaited<ReturnType<typeof listCreatorSubmissions>>[number];
const statusLabel = (value: string) => ({ DRAFT: 'Draft', SUBMITTED: 'In Review', PROCESSING: 'Processing', READY_FOR_CREATOR_REVIEW: 'Ready to Review', CHANGES_REQUESTED: 'Changes Requested', REJECTED: 'Rejected', PUBLISHED: 'Published' }[value] ?? value);

export function CreatorWorkspace({ profile }: { profile: CreatorProfile }) {
  const [tab, setTab] = useState<Tab>('Dashboard'); const [dashboard, setDashboard] = useState<CreatorDashboard | null>(null); const [earn, setEarn] = useState<CreatorMonetization | null>(null); const [verification, setVerification] = useState<CreatorVerification | null>(null); const [submissions, setSubmissions] = useState<Submission[]>([]); const [stories, setStories] = useState<Awaited<ReturnType<typeof getCreatorStories>>>([]); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { const [metrics, own, publicStories, monetization, verified] = await Promise.all([getCreatorDashboard(), listCreatorSubmissions(), getCreatorStories(), getCreatorMonetization(), getCreatorVerification()]); setDashboard(metrics); setSubmissions(own); setStories(publicStories); setEarn(monetization); setVerification(verified); }, []);
  useEffect(() => { const timer = setTimeout(() => void load().catch(() => undefined), 0); return () => clearTimeout(timer); }, [load]);
  async function submit(item: Submission) { try { const detail = await (await import('@/services/api')).getCreatorSubmission(item.id); const genres = (detail.submission_genres ?? []).map((genre) => genre.genre_id); if (!detail.source_storage_key || !genres.length || !detail.rights_declaration) { Alert.alert('Incomplete draft', 'Add a manuscript, genre, and rights declaration first.'); return; } await submitCreatorSubmissionDirect(item.id, { title: detail.title, language: detail.language ?? 'en', genreIds: genres, rightsDeclaration: detail.rights_declaration, declarationVersion: 'v1', description: detail.description ?? undefined }); await load(); } catch { Alert.alert('Unable to submit', 'Please complete the draft and try again.'); } }
  return <View style={styles.shell}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load().finally(() => setRefreshing(false)); }} />}><View style={styles.header}><Pressable onPress={() => router.replace('/(tabs)' as never)}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.brand}>PlayBook Creator</Text><Pressable onPress={() => router.push('/creator-submit' as never)}><Text style={styles.create}>+ Create</Text></Pressable></View>{tab === 'Dashboard' ? <Dashboard data={dashboard} /> : tab === 'Content' ? <Content drafts={submissions} stories={stories} submit={submit} /> : tab === 'Earn' ? <CreatorEarnPanel data={earn} styles={styles} accept={() => void acceptCreatorGuidelines('v1').then(load)} apply={() => void applyForMonetization().then(load)} /> : tab === 'Profile' ? <OwnerProfile profile={profile} verification={verification} apply={() => void applyForCreatorVerification().then(load)} /> : <Dashboard data={dashboard} />}</ScrollView><View style={styles.nav}>{(['Dashboard', 'Content', 'Analytics', 'Earn', 'Profile'] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={styles.navItem}><Text style={[styles.navText, tab === item && styles.active]}>{item}</Text></Pressable>)}</View></View>;
}
function Dashboard({ data }: { data: CreatorDashboard | null }) { return <><Text style={styles.title}>Dashboard</Text>{[['Published stories', data?.publishedStories ?? 0], ['Qualified listening hours', `${((data?.listeningSeconds ?? 0) / 3600).toFixed(2)}`], ['Unique listeners', data?.uniqueListeners ?? 0], ['Followers', data?.followers ?? 0]].map(([label, value]) => <View key={String(label)} style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.value}>{String(value)}</Text></View>)}</>; }
function Content({ drafts, stories, submit }: { drafts: Submission[]; stories: Awaited<ReturnType<typeof getCreatorStories>>; submit: (item: Submission) => void }) { return <><Text style={styles.title}>Content</Text>{drafts.map((item) => <View key={item.id} style={styles.row}><Text style={styles.value}>{item.title}</Text><Text style={styles.muted}>{statusLabel(item.status)}</Text>{item.status === 'DRAFT' ? <View style={styles.actions}><Pressable onPress={() => router.push(`/creator-content-edit?submissionId=${item.id}` as never)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => Alert.alert('Archive draft?', 'This draft will leave your active content list.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: () => void deleteCreatorSubmission(item.id).then(() => undefined) }])}><Text style={styles.danger}>Archive</Text></Pressable><Pressable onPress={() => void submit(item)}><Text style={styles.action}>Submit</Text></Pressable></View> : null}</View>)}{stories.filter((item) => item.status === 'PUBLISHED').map((item) => <View key={item.id} style={styles.row}><Text style={styles.value}>{item.title}</Text><Text style={styles.muted}>Published · {item.visibility}</Text><View style={styles.actions}><Pressable onPress={() => router.push(`/creator-content-edit?submissionId=${item.creator_submission_id}` as never)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => Alert.alert('Unpublish this story?', 'It will no longer be publicly available on PlayBook.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Unpublish', style: 'destructive', onPress: () => void unpublishCreatorSubmission(item.creator_submission_id ?? '').catch(() => Alert.alert('Unable to unpublish', 'Please try again.')) }])}><Text style={styles.danger}>Unpublish</Text></Pressable></View></View>)}</>; }
function OwnerProfile({ profile, verification, apply }: { profile: CreatorProfile; verification: CreatorVerification | null; apply: () => void }) { return <><Text style={styles.title}>{profile.display_name}<VerifiedBadge status={verification?.status} /></Text><Text style={styles.muted}>{profile.followerCount ?? 0} followers</Text><Text style={styles.muted}>{verification?.status ?? 'NOT_APPLIED'}</Text>{verification?.status === 'NOT_APPLIED' ? <Pressable onPress={apply}><Text style={styles.action}>Apply for Verification</Text></Pressable> : null}</>; }
const styles = StyleSheet.create({ shell: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.five, paddingBottom: 100 }, header: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three, minHeight: 52 }, back: { color: Colors.text, fontSize: 32 }, brand: { color: Colors.text, fontWeight: '800', fontSize: 20, flex: 1 }, create: { color: Colors.accentSecondary, fontWeight: '800' }, title: { color: Colors.text, fontSize: 28, fontWeight: '800', marginVertical: Spacing.five }, metric: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Colors.elevated, paddingVertical: Spacing.three }, row: { borderBottomWidth: 1, borderBottomColor: Colors.elevated, paddingVertical: Spacing.four }, value: { color: Colors.text, fontWeight: '800', marginVertical: Spacing.one }, muted: { color: Colors.textSecondary, marginVertical: Spacing.one }, actions: { flexDirection: 'row', gap: Spacing.four, marginTop: Spacing.two }, action: { color: Colors.accentSecondary, fontWeight: '800', marginVertical: Spacing.three }, danger: { color: Colors.danger, fontWeight: '800', marginVertical: Spacing.three }, section: { color: Colors.text, fontSize: 20, fontWeight: '800' }, nav: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 76, flexDirection: 'row', backgroundColor: Colors.background, borderTopWidth: 1, borderTopColor: Colors.elevated }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' }, navText: { color: Colors.textSecondary, fontSize: 11 }, active: { color: Colors.text } });
