import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ContinueListeningCard } from '@/components/books/continue-listening-card';
import { BookCard } from '@/components/books/book-card';
import { SectionHeader } from '@/components/common/section-header';
import { mockBooks } from '@/data/mock-books';
import { Colors, Spacing } from '@/constants/theme';

export default function HomeScreen() { const current = mockBooks[0]; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>FRIDAY, OCTOBER 2</Text><Text style={styles.heading}>Good afternoon, Alex.</Text><Text style={styles.body}>What will you listen to today?</Text><View style={styles.section}><SectionHeader title="Continue listening" /><ContinueListeningCard book={current} /></View><View style={styles.section}><SectionHeader title="Recently added" href="/library" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{mockBooks.slice(0, 4).map((book) => <BookCard key={book.id} book={book} />)}</ScrollView></View><View style={styles.section}><SectionHeader title="Your library" /><View style={styles.shortcuts}><Text style={styles.shortcut}>♡ Favorites</Text><Text style={styles.shortcut}>↓ Downloaded</Text><Text style={styles.shortcut}>✓ Finished</Text></View></View><View style={styles.note}><Text style={styles.noteTitle}>Read when you can. Listen when you can’t.</Text><Text style={styles.noteBody}>Your next chapter is ready whenever you are.</Text></View></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 150 }, eyebrow: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, heading: { color: Colors.text, fontSize: 30, lineHeight: 36, fontWeight: '800', marginTop: Spacing.three }, body: { color: Colors.textSecondary, fontSize: 16, marginTop: Spacing.two }, section: { marginTop: Spacing.nine }, rail: { gap: Spacing.three }, shortcuts: { flexDirection: 'row', gap: Spacing.two, flexWrap: 'wrap' }, shortcut: { color: Colors.text, backgroundColor: Colors.surface, borderRadius: 14, paddingHorizontal: Spacing.three, paddingVertical: Spacing.four, fontSize: 13, fontWeight: '700' }, note: { marginTop: Spacing.nine, borderRadius: 16, padding: Spacing.five, backgroundColor: Colors.elevated }, noteTitle: { color: Colors.text, fontSize: 18, fontWeight: '800' }, noteBody: { color: Colors.textSecondary, fontSize: 14, marginTop: Spacing.two } });
