import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ContinueListeningCard } from '@/components/books/continue-listening-card';
import { BookCard } from '@/components/books/book-card';
import { SectionHeader } from '@/components/common/section-header';
import { mockBooks } from '@/data/mock-books';
import { Colors, Spacing } from '@/constants/theme';
import { getRecommendations, type CatalogResult } from '@/services/api';

export default function HomeScreen() {
  const [recommendations, setRecommendations] = useState<CatalogResult[]>([]); const [recommendationError, setRecommendationError] = useState(false);
  useEffect(() => { void getRecommendations().then(setRecommendations).catch(() => setRecommendationError(true)); }, []);
  const current = mockBooks[0];
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>FRIDAY, OCTOBER 2</Text><Text style={styles.heading}>Good afternoon, Alex.</Text><Text style={styles.body}>What will you listen to today?</Text><View style={styles.section}><SectionHeader title="Continue listening" /><ContinueListeningCard book={current} /></View>{recommendations.length ? <View style={styles.section}><SectionHeader title="For you" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{recommendations.map((item) => <Pressable key={item.id} style={styles.recommendation} onPress={() => router.push(`/catalog/${item.id}` as never)}><View style={styles.cover}><Text style={styles.coverText}>{item.title.slice(0, 16)}</Text></View><Text numberOfLines={2} style={styles.recommendationTitle}>{item.title}</Text><Text numberOfLines={1} style={styles.author}>{item.author_display_name ?? 'PlayBook story'}</Text></Pressable>)}</ScrollView></View> : <View style={styles.section}><SectionHeader title="For you" /><Text style={styles.empty}>{recommendationError ? "We couldn't load recommendations." : 'No stories are available yet.'}</Text></View>}<View style={styles.section}><SectionHeader title="Recently added" href="/library" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{mockBooks.slice(0, 4).map((book) => <BookCard key={book.id} book={book} />)}</ScrollView></View><View style={styles.section}><SectionHeader title="Your library" /><View style={styles.shortcuts}><Text style={styles.shortcut}>♡ Favorites</Text><Text style={styles.shortcut}>↓ Downloaded</Text><Text style={styles.shortcut}>✓ Finished</Text></View></View><View style={styles.note}><Text style={styles.noteTitle}>Read when you can. Listen when you can’t.</Text><Text style={styles.noteBody}>Your next chapter is ready whenever you are.</Text></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 150 }, eyebrow: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, heading: { color: Colors.text, fontSize: 30, lineHeight: 36, fontWeight: '800', marginTop: Spacing.three }, body: { color: Colors.textSecondary, fontSize: 16, marginTop: Spacing.two }, section: { marginTop: Spacing.nine }, rail: { gap: Spacing.three }, recommendation: { width: 148 }, cover: { width: 148, height: 148, borderRadius: 14, padding: Spacing.three, justifyContent: 'flex-end', backgroundColor: Colors.elevated }, coverText: { color: Colors.text, fontSize: 20, fontWeight: '900' }, recommendationTitle: { color: Colors.text, fontSize: 14, lineHeight: 19, fontWeight: '700', marginTop: Spacing.two }, author: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 }, empty: { color: Colors.textSecondary, backgroundColor: Colors.surface, borderRadius: 14, padding: Spacing.four }, shortcuts: { flexDirection: 'row', gap: Spacing.two, flexWrap: 'wrap' }, shortcut: { color: Colors.text, backgroundColor: Colors.surface, borderRadius: 14, paddingHorizontal: Spacing.three, paddingVertical: Spacing.four, fontSize: 13, fontWeight: '700' }, note: { marginTop: Spacing.nine, borderRadius: 16, padding: Spacing.five, backgroundColor: Colors.elevated }, noteTitle: { color: Colors.text, fontSize: 18, fontWeight: '800' }, noteBody: { color: Colors.textSecondary, fontSize: 14, marginTop: Spacing.two } });
