import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/components/common/primary-button';
import { useAuth } from '@/providers/auth-provider';
import { mockBooks } from '@/data/mock-books';
import { Colors, PersistentPlayerContentInset, Spacing } from '@/constants/theme';
import { getCreatorProfile, type CreatorProfile } from '@/services/api';
const items = ['Subscription', 'Listening', 'Preferences', 'Privacy', 'Help'];
export default function ProfileScreen() {
  const { user, profile, signOut } = useAuth(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [creator, setCreator] = useState<CreatorProfile | null>(null);
  useEffect(() => { if (user) void getCreatorProfile().then(setCreator).catch(() => setCreator(null)); }, [user]);
  if (!user) return <SafeAreaView style={styles.safe}><View style={styles.guest}><Text style={styles.eyebrow}>YOUR SPACE</Text><Text style={styles.heading}>Profile</Text><Text style={styles.title}>Create your PlayBook account</Text><Text style={styles.body}>Save your library and listening progress across devices.</Text><PrimaryButton title="Sign in or create account" onPress={() => router.push('/(auth)/sign-in')} /></View></SafeAreaView>;
  const displayName = profile?.display_name || user.user_metadata.display_name || 'Listener'; const creatorRoute = creator?.status === 'PENDING' ? '/creator-profile' : creator?.status === 'ACTIVE' ? '/creator-studio' : '/creator-profile'; const creatorLabel = creator?.status === 'PENDING' ? 'Creator application · Awaiting approval' : creator?.status === 'ACTIVE' ? 'Creator Studio' : 'Become a Creator';
  async function logout() { setLoading(true); setError(null); try { await signOut(); } catch { setError('We could not sign you out. Please try again.'); } finally { setLoading(false); } }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR SPACE</Text><Text style={styles.heading}>Profile</Text><View style={styles.user}><View style={styles.avatar}><Text style={styles.avatarText}>{displayName.charAt(0).toUpperCase()}</Text></View><View><Text style={styles.name}>{displayName}</Text><Text style={styles.email}>{user.email ?? ''}</Text></View><Text style={styles.plan}>Free</Text></View><View style={styles.stats}><Stat label="Listening this week" value="2h 48m" /><Stat label="Books completed" value={String(mockBooks.filter((book) => book.progress === 100).length)} /><Stat label="Saved memories" value="12" /></View><Text style={styles.accountHeading}>Account</Text><PrimaryButton title="Edit Profile" onPress={() => router.push('/profile-edit')} /><View style={styles.menu}>{items.map((item) => item === 'Help' ? <Pressable key={item} style={styles.menuItem} onPress={() => router.push('/help' as never)}><Text style={styles.menuLabel}>{item}<Text style={styles.chevron}>›</Text></Text></Pressable> : <Text key={item} style={styles.menuItem}>{item}<Text style={styles.chevron}>›</Text></Text>)}<Pressable style={styles.menuItem} onPress={() => router.push(creatorRoute as never)}><Text style={styles.menuLabel}>{creatorLabel}<Text style={styles.chevron}>›</Text></Text></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel="Sign out" disabled={loading} onPress={() => Alert.alert('Sign out?', "You'll need to sign in again to access your library and listening progress.", [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign Out', style: 'destructive', onPress: () => void logout() }])} style={styles.signOut}>{loading ? <ActivityIndicator color={Colors.danger} /> : <Text style={styles.signOutText}>Sign Out</Text>}</Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView></SafeAreaView>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: PersistentPlayerContentInset }, guest: { flex: 1, padding: Spacing.six, justifyContent: 'center' }, eyebrow: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, heading: { color: Colors.text, fontSize: 32, fontWeight: '800', marginTop: Spacing.two }, title: { color: Colors.text, fontSize: 22, fontWeight: '800', marginTop: Spacing.seven }, body: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24, marginTop: Spacing.two }, user: { backgroundColor: Colors.surface, borderRadius: 16, padding: Spacing.four, marginTop: Spacing.six, flexDirection: 'row', alignItems: 'center', gap: Spacing.three }, avatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: Colors.accent, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: Colors.text, fontSize: 22, fontWeight: '800' }, name: { color: Colors.text, fontSize: 18, fontWeight: '800' }, email: { color: Colors.textSecondary, fontSize: 13 }, plan: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', marginLeft: 'auto' }, stats: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: Spacing.five }, stat: { flex: 1 }, value: { color: Colors.text, fontSize: 20, fontWeight: '800' }, label: { color: Colors.textSecondary, fontSize: 11 }, accountHeading: { color: Colors.text, fontSize: 18, fontWeight: '800', marginBottom: Spacing.three }, menu: { backgroundColor: Colors.surface, borderRadius: 16, paddingHorizontal: Spacing.four, marginTop: Spacing.five }, menuItem: { color: Colors.text, fontSize: 15, paddingVertical: Spacing.four, borderBottomWidth: 1, borderBottomColor: Colors.elevated }, menuLabel: { color: Colors.text, fontSize: 15 }, chevron: { color: Colors.textSecondary, fontSize: 22 }, signOut: { minHeight: 52, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.three }, signOutText: { color: Colors.danger, fontSize: 15, fontWeight: '800' }, error: { color: Colors.danger, textAlign: 'center' } });
