import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors, Spacing } from '@/constants/theme';
import { searchCatalog, type CatalogResult } from '@/services/api';

export default function SearchScreen() { const [query, setQuery] = useState(''); const [results, setResults] = useState<CatalogResult[]>([]); const [loading, setLoading] = useState(false); useEffect(() => { if (!query.trim()) { const clearTimer = setTimeout(() => setResults([]), 0); return () => clearTimeout(clearTimer); } const timer = setTimeout(() => { setLoading(true); void searchCatalog(query).then((data) => setResults(data.content)).catch(() => setResults([])).finally(() => setLoading(false)); }, 300); return () => clearTimeout(timer); }, [query]); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>DISCOVER</Text><Text style={styles.heading}>Search</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search stories and creators" placeholderTextColor={Colors.textSecondary} style={styles.search} autoCapitalize="none" />{loading ? <ActivityIndicator color={Colors.accentSecondary} style={styles.loading} /> : null}<Text style={styles.sectionTitle}>{query ? 'Stories' : 'Browse by Genre'}</Text>{query ? results.map((item) => <Pressable key={item.id} onPress={() => router.push(`/catalog/${item.id}` as never)} style={styles.result}><Text style={styles.resultTitle}>{item.title}</Text><Text style={styles.resultMeta}>{item.author_display_name ?? 'PlayBook creator'} · {item.content_type}</Text></Pressable>) : <View style={styles.genres}>{['Horror', 'Romance', 'Mystery', 'Fantasy', 'Adventure', 'Self Growth'].map((genre) => <Text key={genre} style={styles.genre}>{genre}</Text>)}</View>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.six, paddingBottom: 120 }, eyebrow: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, heading: { color: Colors.text, fontSize: 32, fontWeight: '800', marginTop: Spacing.two }, search: { height: 50, backgroundColor: Colors.surface, color: Colors.text, borderRadius: 14, paddingHorizontal: Spacing.four, marginTop: Spacing.five }, loading: { marginTop: Spacing.four }, sectionTitle: { color: Colors.text, fontSize: 20, fontWeight: '800', marginTop: Spacing.seven, marginBottom: Spacing.three }, genres: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two }, genre: { color: Colors.text, backgroundColor: Colors.surface, paddingHorizontal: Spacing.four, paddingVertical: Spacing.three, borderRadius: 999 }, result: { backgroundColor: Colors.surface, padding: Spacing.four, borderRadius: 14, marginBottom: Spacing.two }, resultTitle: { color: Colors.text, fontSize: 16, fontWeight: '800' }, resultMeta: { color: Colors.textSecondary, marginTop: Spacing.one, fontSize: 13 } });
