import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Colors, Spacing } from '@/constants/theme';
import { getCreatorSubmission, publishCreatorSubmission } from '@/services/api';

export default function CreatorSubmissionScreen() {
  const { submissionId } = useLocalSearchParams<{ submissionId: string }>(); const [submission, setSubmission] = useState<Awaited<ReturnType<typeof getCreatorSubmission>> | null>(null); const [loading, setLoading] = useState(true); const [publishing, setPublishing] = useState(false);
  useEffect(() => { if (submissionId) void getCreatorSubmission(submissionId).then(setSubmission).catch(() => Alert.alert('Unable to load content', 'Try again later.')).finally(() => setLoading(false)); }, [submissionId]);
  async function publish() { if (!submissionId) return; setPublishing(true); try { await publishCreatorSubmission(submissionId); setSubmission(await getCreatorSubmission(submissionId)); } catch { Alert.alert('Unable to publish', 'This story is not ready to publish.'); } finally { setPublishing(false); } }
  if (loading) return <SafeAreaView style={styles.safe}><ActivityIndicator color={Colors.accentSecondary} /></SafeAreaView>;
  if (!submission) return <SafeAreaView style={styles.safe}><Text style={styles.error}>Content unavailable.</Text></SafeAreaView>;
  const editable = submission.status === 'DRAFT' || submission.status === 'CHANGES_REQUESTED'; const genres = submission.submission_genres.map((item) => item.genres?.name).filter(Boolean).join(', '); const ready = submission.status === 'READY_FOR_CREATOR_REVIEW';
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><View style={styles.topActions}>{editable ? <Pressable accessibilityRole="button" accessibilityLabel="Edit content" onPress={() => router.push(`/creator-content-edit?submissionId=${submission.id}` as never)}><Text style={styles.icon}>✎</Text></Pressable> : null}<Text style={styles.icon}>⋮</Text></View></View><View style={styles.cover}><Text style={styles.coverText}>{submission.title.slice(0, 1)}</Text></View><Text style={styles.title}>{submission.title}</Text><Text style={styles.status}>{submission.status}</Text><View style={styles.info}><Text style={styles.label}>Visibility</Text><Text style={styles.value}>{submission.status === 'PUBLISHED' ? 'Public' : 'Draft / review'}</Text><Text style={styles.label}>Language</Text><Text style={styles.value}>{submission.language || 'Not specified'}</Text><Text style={styles.label}>Genres</Text><Text style={styles.value}>{genres || 'Not specified'}</Text></View><Text style={styles.heading}>Analytics</Text><Text style={styles.body}>Qualified listens, listening time, completion, favorites, and shares appear after publication.</Text>{ready ? <Pressable disabled={publishing} style={styles.button} onPress={() => void publish()}><Text style={styles.buttonText}>{publishing ? 'Publishing…' : 'Publish'}</Text></Pressable> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { padding: Spacing.five, paddingBottom: 100 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { color: Colors.text, fontSize: 32 }, topActions: { flexDirection: 'row', gap: Spacing.five }, icon: { color: Colors.text, fontSize: 26 }, cover: { height: 190, backgroundColor: Colors.elevated, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.three }, coverText: { color: Colors.text, fontSize: 72, fontWeight: '800' }, title: { color: Colors.text, fontSize: 28, fontWeight: '800', marginTop: Spacing.five }, status: { color: Colors.accentSecondary, marginTop: Spacing.two, fontWeight: '800' }, info: { marginTop: Spacing.five, borderTopWidth: 1, borderTopColor: Colors.elevated }, label: { color: Colors.textSecondary, marginTop: Spacing.four }, value: { color: Colors.text, fontSize: 16, marginTop: Spacing.one }, heading: { color: Colors.text, fontSize: 22, fontWeight: '800', marginTop: Spacing.seven }, body: { color: Colors.textSecondary, lineHeight: 22, marginTop: Spacing.two }, button: { backgroundColor: Colors.accentSecondary, padding: Spacing.four, alignItems: 'center', marginTop: Spacing.five }, buttonText: { color: Colors.background, fontWeight: '800' }, error: { color: Colors.danger } });
