import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import type { ReactNode } from 'react';

import { Colors, Spacing } from '@/constants/theme';

export function AuthShell({ eyebrow, title, subtitle, children, footer }: { eyebrow: string; title: string; subtitle: string; children: ReactNode; footer: ReactNode }) { return <KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text><View style={styles.form}>{children}</View><View style={styles.footer}>{footer}</View></ScrollView></KeyboardAvoidingView>; }
export function AuthDivider() { return <View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>or</Text><View style={styles.line} /></View>; }
export function AuthError({ message }: { message: string | null }) { return message ? <Text accessibilityRole="alert" style={styles.error}>{message}</Text> : null; }
export function AuthFooterLink({ prompt, label, href }: { prompt: string; label: string; href: '/sign-in' | '/sign-up' }) { return <Text style={styles.footerText}>{prompt} <Link href={href} style={styles.link}>{label}</Link></Text>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.background }, content: { flexGrow: 1, padding: Spacing.six, paddingTop: Spacing.nine, paddingBottom: Spacing.seven }, eyebrow: { color: Colors.accentSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, title: { color: Colors.text, fontSize: 32, lineHeight: 38, fontWeight: '800', marginTop: Spacing.three }, subtitle: { color: Colors.textSecondary, fontSize: 16, lineHeight: 24, marginTop: Spacing.two }, form: { marginTop: Spacing.five }, footer: { marginTop: 'auto', paddingTop: Spacing.seven }, footerText: { color: Colors.textSecondary, textAlign: 'center', fontSize: 14 }, link: { color: Colors.accentSecondary, fontWeight: '800' }, divider: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three, marginVertical: Spacing.five }, line: { flex: 1, height: 1, backgroundColor: Colors.elevated }, or: { color: Colors.textSecondary, fontSize: 12 }, error: { color: Colors.danger, fontSize: 14, lineHeight: 20, marginTop: Spacing.three } });
